FROM node:20-slim AS base

WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install

COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

EXPOSE 3000
ENV PORT=3000
CMD ["npm", "run", "start"]
